version: "3.3"
   
services:
  api:
    build: .
    command: python manage.py runserver -p 5000 -h 0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
      - broker
    environment: 
      BROKER_URL: amqp://user:password@broker:5672/
      DB_URL: "db+postgresql://db_user:db_password@db:5432/db"
      DATABASE_URL: "postgresql://db_user:db_password@db:5432/db"
      APP_SETTINGS: config.DevelopmentConfig
    
  worker:
    build: .
    command: python -m celery -A worker worker -l INFO
    environment: 
      BROKER_URL: amqp://user:password@broker:5672/
      DB_URL: "db+postgresql://db_user:db_password@db:5432/db"
      APP_SETTINGS: config.DevelopmentConfig
    volumes:
      - .:/code
  
  broker:
    image: rabbitmq
    environment: 
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      
  db:
    image: postgres
    ports:
      - "9876:5432"
    environment: 
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
