FROM nvidia/cuda:11.2.1-devel
RUN apt-get update
RUN apt-get install -y python3 python3-pip python-is-python3
RUN apt install -y python3-dev libpq-dev build-essential
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY Pipfile /code/
COPY Pipfile.lock /code/
RUN pip3 install pipenv \
 && pipenv install --deploy --system --ignore-pipfile
RUN python3 -m spacy download es_core_news_sm
RUN python3 -c "import nltk;nltk.download('stopwords')"
COPY . /code/