# Generated by Django 3.2.8 on 2021-10-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=30)),
                ('task_parameters', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_model', models.CharField(max_length=30)),
                ('execution_file', models.BinaryField()),
                ('parameters', models.JSONField()),
                ('train_results', models.JSONField()),
                ('test_results', models.JSONField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Experimenter.experiment')),
            ],
        ),
    ]
