# Generated by Django 3.2.4 on 2021-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experimenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(max_length=100)),
                ('instance_path', models.CharField(max_length=200)),
                ('parameters', models.JSONField()),
                ('test_results', models.JSONField()),
            ],
        ),
    ]
