"""empty message

Revision ID: 4541281cc0f3
Revises: 
Create Date: 2021-03-24 12:18:34.597460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4541281cc0f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquitecturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('params_schema', sa.JSON(), nullable=False),
    sa.Column('class_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('train', sa.PickleType(), nullable=False),
    sa.Column('val', sa.PickleType(), nullable=False),
    sa.Column('test', sa.PickleType(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DONE', 'ERROR', 'RUNNING', name='taskstatus'), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experimentos_metrics',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experimentos.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metricas.id'], ),
    sa.PrimaryKeyConstraint('experiment_id', 'metric_id')
    )
    op.create_table('modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('path', sa.String(length=120), nullable=False),
    sa.Column('arc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arc'], ['arquitecturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelos_experimentos',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('hiperparametros', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experimentos.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['modelos.id'], ),
    sa.PrimaryKeyConstraint('model_id', 'experiment_id')
    )
    op.create_table('resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('TRAIN', 'VAL', 'TEST', name='resultkind'), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experimentos.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metricas.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['modelos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados')
    op.drop_table('modelos_experimentos')
    op.drop_table('modelos')
    op.drop_table('experimentos_metrics')
    op.drop_table('schemas')
    op.drop_table('metricas')
    op.drop_table('experimentos')
    op.drop_table('datasets')
    op.drop_table('arquitecturas')
    # ### end Alembic commands ###
